#!/bin/sh
set -eu

cat > /usr/share/nginx/html/config.js <<EOF
window.__AXIOMNODE_CONFIG__ = {
  VITE_API_BASE_URL: "${VITE_API_BASE_URL:-http://localhost:7005}",
  VITE_EDGE_API_TOKEN: "${VITE_EDGE_API_TOKEN:-}",
  VITE_AUTH_MODE: "${VITE_AUTH_MODE:-dev}",
  VITE_ADMIN_DEV_UID: "${VITE_ADMIN_DEV_UID:-admin-dev-uid}",
  VITE_FIREBASE_API_KEY: "${VITE_FIREBASE_API_KEY:-}",
  VITE_FIREBASE_AUTH_DOMAIN: "${VITE_FIREBASE_AUTH_DOMAIN:-}",
  VITE_FIREBASE_PROJECT_ID: "${VITE_FIREBASE_PROJECT_ID:-}",
  VITE_FIREBASE_STORAGE_BUCKET: "${VITE_FIREBASE_STORAGE_BUCKET:-}",
  VITE_FIREBASE_MESSAGING_SENDER_ID: "${VITE_FIREBASE_MESSAGING_SENDER_ID:-}",
  VITE_FIREBASE_APP_ID: "${VITE_FIREBASE_APP_ID:-}",
  VITE_FIREBASE_MEASUREMENT_ID: "${VITE_FIREBASE_MEASUREMENT_ID:-}"
};
EOF
